const keyBase = [
  {eng: '`', rus: '`', uniLang: true, secondFunc: '~'},
  {eng: '1', rus: '1', uniLang: true, secondFunc: '!'},
  {eng: '2', rus: '2', uniLang: true, secondFunc: '@'},
  {eng: '3', rus: '3', uniLang: true, secondFunc: '#'},
  {eng: '4', rus: '4', uniLang: true, secondFunc: '$'},
  {eng: '5', rus: '5', uniLang: true, secondFunc: '%'},
  {eng: '6', rus: '6', uniLang: true, secondFunc: '^'},
  {eng: '7', rus: '7', uniLang: true, secondFunc: '&'},
  {eng: '8', rus: '8', uniLang: true, secondFunc: '*'},
  {eng: '9', rus: '9', uniLang: true, secondFunc: '('},
  {eng: '0', rus: '0', uniLang: true, secondFunc: ')'},
  {eng: '-', rus: '-', uniLang: true, secondFunc: '_'},
  {eng: '=', rus: '=', uniLang: true, secondFunc: '+'},
  {eng: 'Backspace', rus: 'Backspase', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'Tab', rus: 'Tab', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'q', rus: 'й', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'w', rus: 'ц', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'e', rus: 'у', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'r', rus: 'к', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 't', rus: 'е', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'y', rus: 'н', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'u', rus: 'г', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'i', rus: 'ш', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'o', rus: 'щ', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'p', rus: 'з', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: '[', rus: 'х', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: ']', rus: 'ъ', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: '\\', rus: '|', uniLang: false, secondFunc: ''},
  {eng: 'Del', rus: 'Del', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'CapsLk', rus: 'CapsLk', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'a', rus: 'ф', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 's', rus: 'ы', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'd', rus: 'в', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'f', rus: 'а', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'g', rus: 'п', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'h', rus: 'р', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'j', rus: 'о', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'k', rus: 'л', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'l', rus: 'д', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: ';', rus: 'ж', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: "\'", rus: 'э', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'Enter', rus: 'Enter', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wider'},
  {eng: 'Shift', rus: 'Shift', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'z', rus: 'я', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'x', rus: 'ч', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'c', rus: 'с', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'v', rus: 'м', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'b', rus: 'и', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'n', rus: 'т', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'm', rus: 'ь', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: ',', rus: 'ь', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: '.', rus: 'б', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: '/', rus: 'ю', uniLang: false, secondFunc: '', additionClass: 'keyboard__btn_char'},
  {eng: 'Up', rus: 'Up', uniLang: true, secondFunc: ''},
  {eng: 'Shift', rus: 'Shift', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'Ctrl', rus: 'Ctrl', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'Win', rus: 'Win', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'Alt', rus: 'Alt', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'Space', rus: 'Space', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_widest'},
  {eng: 'Alt', rus: 'Alt', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
  {eng: 'Left', rus: 'Left', uniLang: true, secondFunc: ''},
  {eng: 'Down', rus: 'Down', uniLang: true, secondFunc: ''},
  {eng: 'Right', rus: 'Right', uniLang: true, secondFunc: ''},
  {eng: 'Ctrl', rus: 'Ctrl', uniLang: true, secondFunc: '', additionClass: 'keyboard__btn_wide'},
];

export default keyBase;
